### ISSUE TITLE
Heading bleading through dropdown

### ISSUE THREAD

**Issue by perifer** [helsingborg-stad/styleguide-web#2]
29b47332 introduced -webkit-perspective that creates the bug in the screenshot.
<img width="324" alt="_lokal_miljo__portalen" src="https://cloud.githubusercontent.com/assets/34488/24030252/3ec0daec-0adc-11e7-9162-c0fe8205a6d7.png">

**Comment by perifer** [comment]
@sebastianthulin have you looked at this? You can see this in various places at intranat.astorp.se.

**Comment by sebastianthulin** [comment]
This was just a precaution gone wrong. Removed it.
