### ISSUE TITLE
Subscribe button hidden on Intranet

### ISSUE THREAD

**Issue by perifer** [helsingborg-stad/styleguide-web#5]
Probably some updated styling from the new meny that have side-effects.
![_lokal_miljo__portalen](https://user-images.githubusercontent.com/34488/27373901-41e3cb56-566a-11e7-8687-52b509c77a98.jpg)

This is how it should look like:

![_lokal_miljo__portalen](https://user-images.githubusercontent.com/34488/27373981-7cf5a232-566a-11e7-8bca-07e2c0715b01.jpg)

**Comment by sebastianthulin** [comment]
This is now resolved.
